### ISSUE TITLE
mpp=solar 0.7.76 PV1 and PV2 current output

### ISSUE THREAD

**Issue by AnKloss** [jblance/mpp-solar#133]
Hello
at 0.7.76 the pv1 and pv2 current output is only 1 A as number by using of PI30MAX.
Possible to get 1 or2 decimal out to?  Example 1.23 A

mfg
Andreas

**Comment by AnKloss** [comment]
![27080](https://user-images.githubusercontent.com/85149594/128295205-68c7f40c-7d20-43fe-8b53-f64202ea6ca2.jpg)

**Comment by jblance** [comment]
It depends on what command you are using - according to the document QPGS0 gives an int, but QPIGS and QPIGS2 give floats

**Comment by AnKloss** [comment]
many thanks, working
![27083](https://user-images.githubusercontent.com/85149594/128442333-22a72fdb-40f6-4b27-8dfd-1da6758c3da9.jpg)
