### ISSUE TITLE
"new" jkbms Protocol changes..

### ISSUE THREAD

**Issue by Scotty-89** [jblance/mpp-solar#138]
hey,

currently i am working on to read out my JKBMS  HW Version 6.X SW Version 6.1.3S (JK-b2a24S15P) over an EPS32 via Bluetooth ;)
it looks not so bad the Basics are working only the responses what i got from the Balancer are not fitting to the "known" types yet..

maybe for some else this could be helpful .. or can help me to find out some more out of it ;) 

this is now how it looks like ..:

["Hex2Str", 4, "Header", ""],
            ["Hex2Str", 1, "Record_Type", ""],
            ["Hex2Int", 1, "Record_Counter", ""],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell01", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell02", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell03", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell04", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell05", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell06", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell07", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell08", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell09", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell10", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell11", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell12", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell13", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell14", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell15", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell16", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell17", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell18", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell19", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell20", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell21", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell22", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell23", "V"],
            ["LittleHex2Short:r/1000", 2, "Voltage_Cell24", "V"],
            ["discard", 4, "Unknown", ""],
            ["LittleHex2Short:r/1000", 2, "Average_Cell_Voltage", "V"],
            ["LittleHex2Short:r/1000", 2, "Delta_Cell_Voltage", "V"],
            ["discard", 2, "Unknown", ""],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell01", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell02", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell03", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell04", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell05", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell06", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell07", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell08", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell09", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell10", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell11", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell12", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell13", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell14", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell15", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell16", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell17", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell18", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell19", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell20", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell21", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell22", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell23", "Ohm"],
            ["LittleHex2Short:r/1000", 2, "Resistance_Cell24", "Ohm"],
            ["discard", 6, "Unknown", ""],
            ["LittleHex2UInt:r/1000", 4, "Battery_Voltage", "V"],
            ["LittleHex2Float", 4, "Battery_Power", "W"],
            ["LittleHex2Float", 4, "Charge_Current", "A"], 
            ["discard", 6, "Unknown", ""],
            ["LittleHex2Short:r/10", 2, "Battery_T1", "°C"],
            ["LittleHex2Short:r/10", 2, "Battery_T2", "°C"],
            ["LittleHex2Short:r/10", 2, "MOS_Temp", "°C"],
			["discard", 2, "Unknown", ""],
			["LittleHex2Short:r/1000", 2, "Balancer Current", "A"], 
			["Hex2Int", 1, "Balancer State", "0 = off; 1 = ON positiv current; ON negativ current"], 
			["Hex2Int", 1, "Percent_Remain", ""],
            ["LittleHex2UInt:r/1000", 4, "Capacity_Remain", ""],  # Unknown6+7
            ["LittleHex2UInt:r/1000", 4, "Nominal_Capacity", ""],  # Unknown8+9
            ["Hex2Str", 4, "Cycle_Count", ""],
			["discard", 6, "Unknown", ""],	
            ["LittleHex2UInt:r/1000", 4, "Capacity_Cycle", ""],  # Unknown10+11
            ["uptime", 3, "Time", ""],
            ["discard", 1, "Unknown", ""],
			["Hex2Int", 1, "Charge State", "0 = off; 1 = ON"], 
			["Hex2Int", 1, "Discharge State", "0 = off; 1 = ON"],
			
            ...
			...
			... 

here also an full response: 

55, AA, EB, 90, 2, F7, B0, E, 9, F, 70, F, 7F, F, CC, E, 47, E, C, F, 39, F, 71, F, AE, E, 6B, E, AB, E, 6E, F, 6A, E, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, FF, 3F, 0, 0, EF, E, 38, 1, 3, 5, 83, 0, 84, 0, 88, 0, 8F, 0, 8E, 0, 91, 0, 88, 0, 8C, 0, 8E, 0, B7, 0, 93, 0, 9A, 0, 8C, 0, 83, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, D, D1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, E7, 0, EA, 0, D, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 9C, 0, 0, 0, 0, 0, 0, AF, 2, 0, 0, 64, 0, 5A, 1, 17, 96, 2, 0, 0, 0, 96, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 1, 0, 0, 0, 23, 4, 0, 0, 0, 0, A6, 2C, 40, 40, 0, 0, 0, 0, 75, 5, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, E6, 6C, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3E, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

after some test i also found ou some more changes but i am not able to understand them 100% ;) 

![Unbenannt](https://user-images.githubusercontent.com/54929714/128705154-1e4f56f9-b185-4d89-8cb2-0d91dc84d7fa.PNG)

**Comment by jblance** [comment]
Im not sure what you are asking - or what you are showing in the image

one of the things i did when i was trying to reverse engineer is to fake the BMS and send messages to the app to confirm that changes delivered the expected answer - that was a huge PITA though but was the only way i found to be certain

**Comment by ulinieto** [comment]
Hello, i had a jkbms 16s working with your mpp-solar. Ununfortunaly i broken it and i've bought a new one but with harware version 8.x, 

The new one doesnt work, are ther any way to make it work again??

**Comment by jblance** [comment]
What does the debug output show?

**Comment by ulinieto** [comment]
Unable to connect to bluetooth

**Comment by jblance** [comment]
Do you have the correct mac address?
Have you restarted bluetooth?
Is anything else connected to the bms?
Does the app connect correctly?

**Comment by ulinieto** [comment]
Do you have the correct mac address? YES
Have you restarted bluetooth? YES
Is anything else connected to the bms? NO
Does the app connect correctly? YES

This what a get at the terminal:

ago 20 23:00:42 raspberrypi systemd[1]: jkbms.service: Service RestartSec=5s expired, scheduling restart.
ago 20 23:00:42 raspberrypi systemd[1]: jkbms.service: Scheduled restart job, restart counter is at 20.
ago 20 23:00:42 raspberrypi systemd[1]: Stopped jkbms is a script for jkbms.
ago 20 23:00:42 raspberrypi systemd[1]: Started jkbms is a script for jkbms.
ago 20 23:02:44 raspberrypi jkbms.py[1636]: Cannot connect to wtfsection with mac c8:47:8c:f3:73:32 - exceeded 3 attempts
ago 20 23:02:44 raspberrypi jkbms.py[1636]: Failed to connect to wtfsection c8:47:8c:f3:73:32
ago 20 23:02:44 raspberrypi systemd[1]: jkbms.service: Succeeded.
ago 20 23:02:49 raspberrypi systemd[1]: jkbms.service: Service RestartSec=5s expired, scheduling restart.
ago 20 23:02:49 raspberrypi systemd[1]: jkbms.service: Scheduled restart job, restart counter is at 21.
ago 20 23:02:49 raspberrypi systemd[1]: Stopped jkbms is a script for jkbms.
ago 20 23:02:49 raspberrypi systemd[1]: Started jkbms is a script for jkbms.
ago 20 23:03:50 raspberrypi jkbms.py[1645]: Traceback (most recent call last):
ago 20 23:03:50 raspberrypi jkbms.py[1645]:   File "/usr/bin/jkbms.py", line 469, in <module>
ago 20 23:03:50 raspberrypi jkbms.py[1645]:     jk.getBLEData()
ago 20 23:03:50 raspberrypi jkbms.py[1645]:   File "/usr/bin/jkbms.py", line 328, in getBLEData
ago 20 23:03:50 raspberrypi jkbms.py[1645]:     characteristicRead = serviceNotify.getCharacteristics(characteristicReadUuid)[0]
ago 20 23:03:50 raspberrypi jkbms.py[1645]: IndexError: list index out of range
ago 20 23:03:50 raspberrypi systemd[1]: jkbms.service: Main process exited, code=exited, status=1/FAILURE
ago 20 23:03:50 raspberrypi systemd[1]: jkbms.service: Failed with result 'exit-code'.
ago 20 23:03:56 raspberrypi systemd[1]: jkbms.service: Service RestartSec=5s expired, scheduling restart.
ago 20 23:03:56 raspberrypi systemd[1]: jkbms.service: Scheduled restart job, restart counter is at 22.
ago 20 23:03:56 raspberrypi systemd[1]: Stopped jkbms is a script for jkbms.
ago 20 23:03:56 raspberrypi systemd[1]: Started jkbms is a script for jkbms.
ago 20 23:03:59 raspberrypi jkbms.py[1653]: Cannot connect to wtfsection with mac c8:47:8c:f3:73:32 - exceeded 3 attempts
ago 20 23:03:59 raspberrypi jkbms.py[1653]: Failed to connect to wtfsection c8:47:8c:f3:73:32

**Comment by jblance** [comment]
Try using the command line first. What version are you running?

**Comment by ulinieto** [comment]
Where can i see what version i'm running?

**Comment by jblance** [comment]
jkbms -v

**Comment by ulinieto** [comment]
Solar Device Command Utility, version: 0.7.54, recent changes: add jk rs232/485 protocol

**Comment by jblance** [comment]
Ok, so fairly new, try

`sudo hcitool lescan`

**Comment by ulinieto** [comment]
I've done the scan and the rasp detects without problem the new jkbms. Thanks for your help but may be I'll try another BMS
