### ISSUE TITLE
build array of commands in __init__.py

### ISSUE THREAD

**Issue by VictorBucha** [jblance/mpp-solar#168]
Not changed ',' for ';'
makes PI17 fail on some commands, which use comma as separator

**Comment by skoky** [comment]
@VictorBucha  I think that you can use `#` as command separator. I have tested this on my PI17 based inverter and it works. Example command I use `sudo  mpp-solar -p /dev/hidraw0 -P PI17  -c GS#PS#MOD` and this executes all 3 commands. Looking into the code I believe it should process commands with comma as well

**Comment by VictorBucha** [comment]
Thank you, but my suggestion was not intended to run 2or 3 commands at once but to execute commands, which have comma in its body. But thanks for this information.
