### ISSUE TITLE
Can't run scripts in Docker : no systemd in Alpine

### ISSUE THREAD

**Issue by audio-catalyst** [jblance/mpp-solar#169]
hi, i was hoping to package these scripts in a docker image, however as the docker default is Alpine linux , there is no systemD.
This makes it really hard to run the service..

Please advise

**Comment by audio-catalyst** [comment]
havent tried that, however the alpine linux distri is extremely small ( 5 mb) and the defacto standard in the docker world.
i'll try and get back to you
________________________________

**Comment by audio-catalyst** [comment]
it uses rc :

https://www.cyberciti.biz/faq/how-to-enable-and-start-services-on-alpine-linux/

goals would be easy fast deployment, integration and run locally in hass.io, run multiple shielded apps on a single device.

basically all reasons for using docker :)
________________________________

**Comment by jblance** [comment]
docker build documented, removal of systemd dependancy in powermon
