### ISSUE TITLE
Need to limit the output using filter

### ISSUE THREAD

**Issue by shanrahul** [jblance/mpp-solar#177]
I'm running `mpp-solar -p /dev/hidraw0 -P PI30 -c QPIGS ` to get the general stats, but i only require some of them. So i went through the options in the mpp-solar usage and found out the `--filter` option , How do we use it? do we have to define a filter first ?

**Comment by jblance** [comment]
It's a regex, so any valid regular expression should work. There is also a
exclfilter option

Filter specifies what to include and exclfilter specifies what to remove
