### ISSUE TITLE
JK BMS JK02 Proto - Dont send "record_type": "01" Messages

### ISSUE THREAD

**Issue by natbesh** [jblance/mpp-solar#180]
I have a JKBMS using the JK02 protocol.
The command i'm using is: jkbms -p <mac> -P JK02 -c getCellData -o json
Every now & then - (seemingly randomly?) a "record_type": "01" "BLE Cell Data inquiry" message will be received instead of the usual "record_type": "02" "getCellData" message.

This "01" message has random values for attributes, which throws off any dashbaords.
i.e Cell voltages are 0.0 to 18.928v,  Battery temp jumps from 25deg to 1,785deg

Easy to filter out in a script - but would be good to make sure these dont go out via MQTT etc

**Comment by jblance** [comment]
should be fixed
