### ISSUE TITLE
Feature Request - Update Inverter Settings

### ISSUE THREAD

**Issue by ziadakiki** [jblance/mpp-solar#220]
I've been using mpp-solar to read the status/settings of my inverter successfully. It would be nice if we could use mpp-solar to change those settings as well (ex. update source priority)

**Comment by jblance** [comment]
Which protocol do you use? Some of them have setting parameters implemented

**Comment by ziadakiki** [comment]
PI30REVO

**Comment by jblance** [comment]
you can try some of the pi30 setter commands, i havent implemented any for
the revo variant yet

**Comment by jblance** [comment]
setter commands added
