### ISSUE TITLE
issue with decoded response

### ISSUE THREAD

**Issue by HyperHubs** [jblance/mpp-solar#244]
I have a problem decoding the response from the QPIGS command in the PI30 protocol.
the inverter on the QPIGS command returns something like this:
`b'(207.1 49.9 229.3 50.0 0848 0754 013 380 51.40 000 052 0035 00.0 000.0 00.00 00016 00010000 00 00 000\x020 010\xcc\x00\r'`

`[b'207.1 ', b'49.9', b'229.3 ', b'50.0', b'0848 ', b'0754', b'013 ', b'380', b'51.40 ', b'000' , b'052 ', b'0035', b'00.0 ', b'000.0', b'00.00 ', b'00016', b'00010000 ', b'00', b'00 ', b'000 \ x020 ', b'010']`

and decode me as below:
```
results: {
'raw_response': ['(207.1 49.9 229.3 50.0 0848 0754 013 380 51.40 000 052 0035 00.0 000.0 00.00 00016 00010000 00 00 000 \ x020 010Ì \ x00 \ r', ''], 
'_command': 'QPIGS' , '_command_description': 'General Status Parameters inquiry', 
'AC Input Voltage': [207.1, 'V'], 
'AC Input Frequency': [49.9, 'Hz'], 
'AC Output Voltage': [229.3, ' V '],
' AC Output Frequency ': [50.0,' Hz '],
' AC Output Apparent Power ': [848,' VA '],
' AC Output Active Power ': [754,' W '],
' AC Output Load ': [13,'% '],
' BUS Voltage ': [380,' V '],
' Battery Voltage ': [51.4,' V '],
' Battery Charging Current ': [0,' A ' ], 
'Battery Capacity': [52, '%'], 
'Inverter Heat Sink Temperature': [35, '° C'], 
'PV Input Current for Battery': [0.0, 'A'], 
'PV Input Voltage ': [0.0,' V '],
' Battery Voltage from SCC ': [0.0,' V '],
' Battery Discharge Current ': [16,' A '],
' Is SBU Priority Version Added ': [0 , 'bool'], 
'Is Configuration Changed': [0, 'bool'], 
'Is SCC Firmware Updated': [0, 'bool'], 
'Is Load On': [1, 'bool'], 
' Is Battery Voltage to Steady W. hile Charging ': [0,' bool '],
' Is Charging On ': [0,' bool '],
' Is SCC Charging On ': [0,' bool '],
' Is AC Charging On ': [0 , 'bool'], 
'RSV1': [0, 'A'], 'RSV2': [0, 'A'], 
'PV Input Power': ['000 \ x020', 'W'], 
'Is Charging to Float ': [0,' bool '],
' Is Switched On ': [1,' bool '],
' Is Reserved ': [0,' bool ']}
```
after generating the CRC for the answer, unfortunately I get an error :(
the problem is the probability
**b'000 \ x020 '**decoded to' **PV Input Power ': [' 000 \ x020 ',' W '],**

could I ask you for help in modifying the protocol so that this strange notation is correct and it is possible to generate the correct CRC

**Comment by jblance** [comment]
sorry i seemed to have missed this issue when it was logged.
did you get it sorted?
do you still need help?
from initial look the initial response looks wrong - is it consistently like that (ie with a hex char in the second to last response field?
