### ISSUE TITLE
Forcing Home Assistant to trigger update event 

### ISSUE THREAD

**Issue by sebmueller** [jblance/mpp-solar#245]
Hello,
I played around with your great implementation :)
I can read out my cheap china inverters (PI30REVO protocoll).

I have a Home Assistant instance running and I am filtering the input values for spikes.

In the night, I had the problem, that many values (e.g. Solar Voltage, Charging current, ...) dont have value changes, because they are 0 all the night. So also my filtered values didnt become updated.

I figured out, that a config value ("force_update": "true") has to be set.

So I changed the hass_mqtt.py (lines 59 + 61)

> payload = f'{{"name": "{name}", "state_topic": "homeassistant/sensor/mpp_{tag}_{key}/state", "unit_of_measurement": "{unit}", "unique_id": "mpp_{tag}_{key}", "state_class": "measurement", "device_class": "power", "force_update": "true"  }}'

> payload = f'{{"name": "{name}", "state_topic": "homeassistant/sensor/mpp_{tag}_{key}/state", "unit_of_measurement": "{unit}", "unique_id": "mpp_{tag}_{key}", "force_update": "true"  }}'

This could also be very interessting for other people. I hope you will include this change.

Kind regards,
Sebastian

**Comment by jblance** [comment]
thanks added in v0.13.1
