### ISSUE TITLE
/dev/ttyS0

### ISSUE THREAD

**Issue by khvalera** [jblance/mpp-solar#270]
mpp-solar -p /dev/ttyS0 -c QPI
2022-11-11 01:45:31,953:ERROR:device:run_command@280: No communications port defined - unable to run command QPI
Parameter                       Value           Unit
error                           No communications port defined - unable to run command QPI

**Comment by jblance** [comment]
You'll need to specify the porttype for this port (the code doesn't
automatically work for this one)

Eg add `--porttype serial`

**Comment by khvalera** [comment]
Thanks, I checked it works!
