### ISSUE TITLE
combining commands in conf file for PI17 inverter

### ISSUE THREAD

**Issue by eloquentvogon** [jblance/mpp-solar#271]
Hi I have been working with this to get mqtt stats over to Home assistant for a LVX6048WP from MPP and I think I am most of the way there, I am getting stats over to HA, but I am missing battery stats, So I am trying to get the commands GS and PS to go through but this error is coming up

`2022-11-14 12:43:24,796:ERROR:device:run_command@305: full_command not found for GS,PS in protocol b'PI17'
Parameter                       Value           Unit
error                           full_command not found for GS,PS in protocol b'PI17'
`

Is this a limitation of PI17 or bad syntax on my part ?

**Comment by eloquentvogon** [comment]
`[LVX6048WP]
protocol=PI17
port=/dev/hidraw0
command=GS,PS
tag=Inverter1
outputs=screen
`

**Comment by jblance** [comment]
What version are you using?
Newer versions use # as the command separator

**Comment by eloquentvogon** [comment]
oh! I was referencing the old config docs from 

https://github.com/jblance/mpp-solar/blob/master/docs/service/mpp-solar.conf.example

Just changed it and worked, thank you! This project has been a savior for me, I could never get proper stats from my inverter until this. I appreciate it
