### ISSUE TITLE
power reading in JK04 via Bluetooth not available? 

### ISSUE THREAD

**Issue by abc2006** [jblance/mpp-solar#292]
Hi, 
after some unsuccessful attempts over RS485 i tried Bluetooth with the builtin BLE of my RPi 4. 
Eventually, it worked, but with the standard JK04 i don't get any currents or total power. As i tried JK02, its working. 
Is there any reason that it is like it is? Or just not figured out, as in protocols/jk04.py some values are named "discard".

Cheers (and thank you), 
Stephan

**Comment by jblance** [comment]
If it worked with JK02 then its likely that this is the correct protocol for your BMS
However you are correct in that there are differences in the amount that has been 'decoded' in each of the BLE JKBMS protocols as it is reverse engineered and not from a documented protocol. 
If you have information about what/where the missing info is, it can be added
