### ISSUE TITLE
Run Daemon for monitoring and issue commands?

### ISSUE THREAD

**Issue by robwolff3** [jblance/mpp-solar#318]
I love the daemon functionality for continuously monitoring my inverter and sending the information to home assistant. Is there a way to do that and issue one off commands to change the configuration on the inverter while the daemon is running?

**Comment by Saentist** [comment]
Start to thing that service need to have micro web server for this things

https://github.com/rossandrews/mpp-solar-api
if both developers @jblance and @rossandrews unite creative power, creature will be good ;)

**Comment by robwolff3** [comment]
Sorry, just now figuring out this is a duplicate of #288 and #135 . Will close.
