### ISSUE TITLE
MQTT_Influx_Grafana :: unknown mpp-solar-option -i

### ISSUE THREAD

**Issue by mmsfla** [jblance/mpp-solar#333]
Hello John,

thanks for your great tool mpp-solar.
I use it on Raspberian in version 0.12.5.
Yesterday I ventured into your MQTT Grafana plugin!
I tested your suggestion for the cronjob where you...

_/usr/local/bin/mpp-solar -q localhost -c QPIGS **-i**_

... use.

However, my version does not know this option -i and responds with ...

![Bildschirmfoto vom 2023-04-11 22-51-20](https://user-images.githubusercontent.com/97156229/231285672-d2e15466-9cc2-4b86-8fe4-9d654ccffe22.png)

What is the -i option supposed to do in your documentation?
Unfortunately, there is no context of mpp-solar in my InfluxDB.
I used the existing -I (info) option instead of -i. This request does not even arrive in the database. So what does your -i option do to make your tool generate correct requests?

Thanks in advance

Best Regards
Frank

**Comment by jblance** [comment]
good question - as far as I can read it was supposed to be `-I` but it just increases the amount of logging you can leave it out
I'll update the docs

**Comment by mmsfla** [comment]
Well, at the right moment for me.
It's almost bedtime in Germany ;-)

**Comment by mmsfla** [comment]
thanks, I'll test that right away

**Comment by mmsfla** [comment]
The command can be executed, but I don't see anything in the database.
I'll look at that again tomorrow.
But otherwise your guide to troubleshooting is great!

Thank you and many greats

**Comment by jblance** [comment]
there is a mpp-solar measurement there
also need to check step by step - before the db there is telegraf, so need to check that for correct functionality and errors

**Comment by mmsfla** [comment]
Exactly. I'll do that tomorrow. ;)
I'll get back to you afterwards.

**Comment by mmsfla** [comment]
Yeah! Everything works so far!
I saved the troubleshooting with trusting God and restarted my Raspi.
After that, in Grafana I also found the inverter data from the mppsolar database. Thank you very much dear John and please continue to delight us with your great software.

**Comment by jblance** [comment]
good news

**Comment by Saentist** [comment]
> Exactly. I'll do that tomorrow. ;) I have already adjusted the cron job...
> 
> ![Bildschirmfoto vom 2023-04-11 23-36-50](https://user-images.githubusercontent.com/97156229/231293866-141c4240-a817-47b7-862c-5b5859e5fce1.png)
> 
> I'll get back to you afterwards.

Why not use `--daemon` option and run as service?

**Comment by jblance** [comment]
also dont add --daemon to the crontab as that will cause a heapo problems
