### ISSUE TITLE
mpp-solar and crontab

### ISSUE THREAD

**Issue by domore85** [jblance/mpp-solar#370]
Hi,
when I use the command:  /home/domin/.local/bin/mpp-solar -p /dev/ttyUSB0 -c QPIGS -o mqtt -q jeedom,
it works . But when I use it in a crontab, the mqtt server doesn't receive anything.

**Comment by Saentist** [comment]
Use screen
```bash
screen /home/domin/.local/bin/mpp-solar -p /dev/ttyUSB0 -c QPIGS -o mqtt -q jeedom --daemon
```

from terminal, use Ctrl+A and Ctrl+D to detach from screen and return to terminal or Ctrl+C to terminate.
it work as background process and pool each 60 seconds
