### ISSUE TITLE
Load on/off command

### ISSUE THREAD

**Issue by pap3rinik** [jblance/mpp-solar#38]
Noticed that there's not a direct command to power on/off the load. Is there a way to achieve this?
Scenario: shut down the loads programmatically.

**Comment by jblance** [comment]
It depends - this software just implements a way to talk to the device (mainly the inverter), so if your inverter has a command to turn on/off the load then the software can achieve this
Some inverters will turn off load passed on a user settable battery voltage - so it could be possible to change this value to get the inverter to turn off the load
