### ISSUE TITLE
EDECOA EM-554A Hybrid Inverter

### ISSUE THREAD

**Issue by pmknowles** [jblance/mpp-solar#393]
Just confirming the software works for the above hybrid inveter using PI30 if you want to add it to the list.

Niggle about installation though the pip install mppsolar seems to install into a hidden folder (in my case /home/philip/.local/bin) which isn't on the path. It may be that I should have started the install in a specific (or different) folder. If that's the case it might be helpful to explain.

I also had issues with getting --daemon to work. In the end I reverted to using this in my /etc/systemd/system/system/mpp-solar.service file.
```
[Unit]
Description=Run EDECOA monitor
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=60
User=philip
ExecStart=/home/philip/.local/bin/mpp-solar -C /home/philip/.local/bin/mpp-solar.conf
[Install]
WantedBy=multi-user.target
```

**Comment by jblance** [comment]
great thanks for the feedback - sorry i missed this previously
