### ISSUE TITLE
EASUN SPL5K - Inverter switches to bypass at 2 kW

### ISSUE THREAD

**Issue by mmsfla** [jblance/mpp-solar#406]
Dear friends,

Maybe someone is reading along who can help me.
My inverter is the type from EASUN mentioned above and should only use the bypass and the connected network of my house when it exceeds 4000 watts or 5000 VA. However, it does it at 2000 watts. What am I doing wrong?

My configuration:
4 * 12 Volt / 100 Ah battery
approx. 1700 watts of solar

Settings SPL5k:

pi@grafana:~ $ mpp-solar --getsettings
------------------------------------------------------------
Parameter                     	Value           Unit
ac_input_voltage              	_230.0          	V_   
ac_input_current              	_21.7           	A_   
ac_output_voltage             	_230.0          	V_   
ac_output_frequency           	_50.0           	Hz_  
ac_output_current             	_21.7           	A_   
ac_output_apparent_power      	_5000           	VA_  
ac_output_active_power        	_4000           	W_   
battery_voltage               	_48.0           	V_   
battery_recharge_voltage      	_44.0           	V_   
battery_under_voltage         	_42.0           	V_   
battery_bulk_charge_voltage   	_56.4           	V_   
battery_float_charge_voltage  	_54.0           	V_   
battery_type                  	_AGM_            	    
max_ac_charging_current       	_10             	A_   
max_charging_current          	_20             	A_   
input_voltage_range           	_Appliance_      	    
output_source_priority        	_Solar first_    	    
charger_source_priority       	_Solar first_    	    
max_parallel_units            	_6              	units_
machine_type                  	_Off Grid_       	    
topology                      	_transformerless_	    
output_mode                   	_single machine output_	    
battery_redischarge_voltage   	_52.0           	V_   
pv_ok_condition               	_As long as one unit of inverters has connect PV, parallel system will consider PV OK_	    
pv_power_balance              	_PV input max power will be the sum of the max charged power and loads power_	    
overload_restart              	_enabled_        	    
over_temperature_restart      	_enabled_        	    
lcd_backlight                 	_enabled_        	    
primary_source_interrupt_alarm	_enabled_        	    
buzzer                        	_disabled_       	    
overload_bypass               	_disabled_       	    
power_saving                  	_disabled_       	    
lcd_reset_to_default          	_disabled_       	    
record_fault_code             	_disabled_

**Comment by jblance** [comment]
you would get more responses if you posted on a solar forum regarding this, this is just a codebase that attempts to talk to the inverter and get information (and for some inverters allows you to change settings)

i dont fully grasp your problem, but at a guess your batteries might be sagging at 2KW to the point that the inverter switches to AC, from my understanding the inverter has a max output of 4KW after which it may fail completely, even in bypass

**Comment by mmsfla** [comment]
I have now been able to identify the problem.
When I bought the battery I ignored the name C100.
So my batteries are "AGM 100Ah C100", which means:
100 Ah at 100 hour discharge.
This explains the switching to bypass when the load is high.
