### ISSUE TITLE
hassd_mqtt does not work with multiple inverters

### ISSUE THREAD

**Issue by rene-dev** [jblance/mpp-solar#437]
the device name passed with -n is only used in the device name, identifier, and model.
this causes homeassist to create a second device with no entitys, and assign the entitys from the second inverter to the first device.
the name should also be used in the state topic, name, and unique_id.

**Comment by rene-dev** [comment]
specifying the name also as -T seems to work.

**Comment by jblance** [comment]
you can also run separate instances of mpp-solar for each inverter
