### ISSUE TITLE
pv_input_current appear to be an integer, needs to be a float

### ISSUE THREAD

**Issue by BarkinSpider** [jblance/mpp-solar#44]
pv_input_current appear to be an integer, needs to be a float. Watchpower shows 40W of power at 70v = 0.57a.
mpp-solar shows 0 for pv_input_current if it less than 1amp
version: 0.7.3 on pi4 
Linux pi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux

**Comment by BarkinSpider** [comment]
![MPP3048](https://user-images.githubusercontent.com/66278762/100406194-2bf9b480-301a-11eb-8964-137955a3fe36.jpg)

**Comment by jblance** [comment]
> pv_input_current appear to be an integer, needs to be a float. Watchpower shows 40W of power at 70v = 0.57a.
> mpp-solar shows 0 for pv_input_current if it less than 1amp
> version: 0.7.3 on pi4
> Linux pi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux

Can you run the command with -I, as the results i have seen are ints (not floats) - perhaps watchpower is calculating the value...
Happy to make it a float, but this wont help if the info is an int

**Comment by jblance** [comment]
Nice dashboard!!

**Comment by BarkinSpider** [comment]
Yes, I see its an integer. Watchpower must use another command to get the fractional amps to get the accurate wattage. Any idea how it does this?

Also, Is there a way to see if the charger is in Bulk or Float mode?

**Comment by jblance** [comment]
Try QPIGS for pv input power
Q1 is they only command i see in PI30 for charge mode, but not all inverters support it.
Does watchpower give charge mode? Might be worth capturing a full run and seeing if there is a command that I haven't implemented.
There are protocol references in the docs directory
