### ISSUE TITLE
install  mppsolar[systemd] fail

### ISSUE THREAD

**Issue by sante85** [jblance/mpp-solar#473]
I have tryed to install on rpi 5 with python 3.12.2

 sudo -H pip3 install mppsolar[systemd]

 sudo -H pip3 install mppsolar[systemd]
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: mppsolar[systemd] in /usr/local/lib/python3.12/site-packages (0.16.26)
Collecting cysystemd>=1.6.0 (from mppsolar[systemd])
  Using cached cysystemd-1.6.0.tar.gz (296 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: paho-mqtt<2.0.0,>=1.6 in /usr/local/lib/python3.12/site-packages (from mppsolar[systemd]) (1.6.1)
Requirement already satisfied: pydantic>=1.8.0 in /usr/local/lib/python3.12/site-packages (from mppsolar[systemd]) (2.6.3)
Requirement already satisfied: pyserial>3 in /usr/local/lib/python3.12/site-packages (from mppsolar[systemd]) (3.5)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.12/site-packages (from pydantic>=1.8.0->mppsolar[systemd]) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in /usr/local/lib/python3.12/site-packages (from pydantic>=1.8.0->mppsolar[systemd]) (2.16.3)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.12/site-packages (from pydantic>=1.8.0->mppsolar[systemd]) (4.10.0)
Building wheels for collected packages: cysystemd
  Building wheel for cysystemd (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cysystemd (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      /tmp/pip-build-env-kpxwjxj9/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'build_requires'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-312
      creating build/lib.linux-aarch64-cpython-312/cysystemd
      copying cysystemd/__init__.py -> build/lib.linux-aarch64-cpython-312/cysystemd
      copying cysystemd/async_reader.py -> build/lib.linux-aarch64-cpython-312/cysystemd
      copying cysystemd/journal.py -> build/lib.linux-aarch64-cpython-312/cysystemd
      copying cysystemd/daemon.py -> build/lib.linux-aarch64-cpython-312/cysystemd
      copying cysystemd/py.typed -> build/lib.linux-aarch64-cpython-312/cysystemd
      running build_ext
      building 'cysystemd._daemon' extension
      creating build/temp.linux-aarch64-cpython-312
      creating build/temp.linux-aarch64-cpython-312/cysystemd
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/usr/local/include/python3.12 -c cysystemd/_daemon.c -o build/temp.linux-aarch64-cpython-312/cysystemd/_daemon.o
      cysystemd/_daemon.c:1202:10: fatal error: systemd/sd-daemon.h: No such file or directory
       1202 | #include <systemd/sd-daemon.h>
            |          ^~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cysystemd
Failed to build cysystemd
ERROR: Could not build wheels for cysystemd, which is required to install pyproject.toml-based projects

**Comment by jblance** [comment]
looks like no prebuilt binary for your system - you will need to build cysystemd from sources - see https://pypi.org/project/cysystemd/#toc-entry-3
