### ISSUE TITLE
Error in test_mppinverter.py

### ISSUE THREAD

**Issue by hotear** [jblance/mpp-solar#5]
In:
     def test_execute_qid_usb_cmd(self):
         """ test execute of QID command (Direct USB connection)"""
-        inverter = mppinverter.mppInverter('/dev/hidraw1')
+        inverter = mppinverter.mppInverter('/dev/hidraw0')

**Comment by jblance** [comment]
Can you provide more information about the error?
Can you provide some detail on your setup?

**Comment by hotear** [comment]
Sorry, was in a hurry when I wrote that.  I've got my 5048MS connected to a
Pi 4 via USB (direct) and it appears (as you say in your readme) as
hidraw0.  When I ran setup.py test, that test didn't seem to be working and
I noticed it was trying to talk to hidraw1 rather than hidraw0 so I changed
it locally and that fixed it for me.  Just thought it was a typo.

**Comment by jblance** [comment]
ok, those tests are mainly for travis code testing anyway - I'll look at amending them a little to work if the device doesnt open
