### ISSUE TITLE
Python version 3.12 rquirement breaks Debian 12 installation

### ISSUE THREAD

**Issue by gianfrdp** [jblance/mpp-solar#502]
I have Debian 12 (current stable release), with python 3.11 (version bundled with debian 12).

If I try to install in venv using 
``
pip install -e "git+https://github.com/jblance/mpp-solar.git#egg=mppsolar"
``
I have following error:
``
ERROR: Package 'mppsolar' requires a different Python: 3.11.2 not in '<4.0,>=3.12'
``

Why required python 3.12? Is it mandatory? Isn't version 3,11 enough?

**Comment by jblance** [comment]
good point - Ive just updated and changed the requirement (in version 0.16.38)
