### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by devyaz** [jblance/mpp-solar#505]
has anyone tried this on ESP32?

**Comment by Saentist** [comment]
There is few ESP devices with can run linux and they are slow.
Guess all need to be rewritten on MicroPython

see this alternative project's
https://github.com/scottwday/InverterOfThings
https://github.com/syssi/esphome-pipsolar
https://github.com/chipsi/esphome-pipsolar-voltronic
https://github.com/syssi/esphome-smg-ii

But not all are updated and compatible with devices as Mpp-solar

**Comment by devyaz** [comment]
am hoping to put the ESP32 in the inverter, connected to the inverter via UART(TTL-RS232) have its own display (16x2) send events via SMS(A9G board)

**Comment by jblance** [comment]
unfortunately not - I started but never made much progress.
the ESPHome work is good from what I hear and can be largely standalone
I think it has the components to do what you need as long as the inverter
is supported

**Comment by devyaz** [comment]
Ok kool, youre very helpful! Ill try when i get time to transpile from C to micropython

**Comment by Saentist** [comment]
> am hoping to put the ESP32 in the inverter, connected to the inverter via UART(TTL-RS232) have its own display (16x2) send events via SMS(A9G board) and controll via SMS(Telegram later on)

https://www.cnx-software.com/2024/08/01/nbiot-lte-m-air-monitor-solar-powered-esp32-s3-multi-sensor-board-with-sim7080g-nb-iot-lte-m-modem/

;) be more solar, be more modern :)
