### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by hotear** [jblance/mpp-solar#6]
Would be great if this worked under python3.

**Comment by jblance** [comment]
What doesnt work?
The travis tests should test 3.6 as well as 2.7?

**Comment by hotear** [comment]
I was getting errors when trying to run it under python3.  One error as related to 208 in mppinverter.py:
os.write(usb0, send)
python3 did not like that send is a string and said it should be bytes like.
When I tweaked that line it then was complaining about line 219:
log.debug('USB read error', e.strerror)
python3 did not seem to think that the exception e had a strerror element.
When I tweaked that line it seemed to run but didn't seem to get any messages to/from the pip.

This is using the direct USB connection hidraw0 on a raspberry pi 4.

**Comment by jblance** [comment]
how did you alter the `os.write` line?
can you run the script in debug mode and include the output please

**Comment by hotear** [comment]
Sorry, this may have been my mistake.  I was running the mpp-solar command line but had altered the first line to make it use python3 instead of python2.  I've been using the actual python modules now under python3 without issue.  I think this can probably be closed.  Nice work btw.

**Comment by jblance** [comment]
ok, thanks for the update
